import type { Metadata } from "next";
import "../globals.css";
import get_theme from "@/components/Theme_Apply";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let theme = await get_theme();

return (
      <html lang="en" data-theme={theme}>
        <body

          className={`text-black antialiased`}
        >
          {children}

        </body>
      </html>
    );
}
