import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import get_theme from "@/components/Theme_Apply";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await get_theme();
  return (
    <html lang="en" data-theme={theme}>
      <body
        className={`font-mono antialiased`}
      >
       {children}
      </body>
    </html>
  );
}
