-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS tel_dir.tbl_department
(
    department_id bigint NOT NULL,
    department_name text COLLATE pg_catalog."default",
    department_head text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    is_exist boolean DEFAULT true,
    CONSTRAINT tbl_department_pkey PRIMARY KEY (department_id)
);

CREATE TABLE IF NOT EXISTS tel_dir.tbl_group
(
    group_id bigint NOT NULL,
    group_name text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    is_exist boolean DEFAULT true,
    CONSTRAINT tbl_group_pkey PRIMARY KEY (group_id)
);

CREATE TABLE IF NOT EXISTS tel_dir.tbl_local
(
    local bigint NOT NULL,
    group_id bigint NOT NULL,
    department_id bigint NOT NULL,
    location_id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    is_exist boolean DEFAULT true,
    CONSTRAINT tbl_local_pkey PRIMARY KEY (local)
);

CREATE TABLE IF NOT EXISTS tel_dir.tbl_location
(
    location_id bigint NOT NULL,
    location_name text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    is_exist boolean NOT NULL DEFAULT true,
    CONSTRAINT tbl_location_pkey PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS tel_dir.tbl_users
(
    uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
    username text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    first_name text COLLATE pg_catalog."default",
    middle_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    is_exist boolean NOT NULL DEFAULT true,
    updated_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT tbl_users_pkey PRIMARY KEY (uuid)
);

ALTER TABLE IF EXISTS tel_dir.tbl_local
    ADD CONSTRAINT tbl_department_tbl_local FOREIGN KEY (department_id)
    REFERENCES tel_dir.tbl_department (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS tel_dir.tbl_local
    ADD CONSTRAINT tbl_local_tbl_group FOREIGN KEY (group_id)
    REFERENCES tel_dir.tbl_group (group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS tel_dir.tbl_local
    ADD CONSTRAINT tbl_location_tbl_local FOREIGN KEY (location_id)
    REFERENCES tel_dir.tbl_location (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;